//! `delocal-engine`: the pure sync engine (DESIGN.md §7, §8 and Appendix B).
//!
//! The engine takes events (scan results, incoming messages, timer ticks) and
//! returns actions (write file, send message, record history). It does no I/O
//! and depends on nothing that does. Time and randomness are inputs:
//! timestamps and fresh identifiers arrive in events, generated by the host.
//!
//! Phase 1 builds this crate up one step at a time (§15). So far:
//!
//! - [`id`]: node, folder and batch identifiers (§4), hostnames (§7.1)
//! - [`version`]: version vectors, comparison, merge, the local-change rule (§7.2)
//! - [`path`]: validated relative paths (§7.1)
//! - [`entry`]: index entries and content equality (§7.1, §7.6)
//! - [`index`]: the per-folder index, local changes, tombstones (§7.1, §7.2, §7.7)

// Tests may unwrap and expect (CLAUDE.md conventions); production code may not.
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

pub mod entry;
pub mod id;
pub mod index;
pub mod path;
pub mod version;

pub use entry::{ContentHash, Entry, Kind, Observed};
pub use id::{BatchId, FolderId, HostName, NodeId};
pub use index::{ChangeKind, Index, IndexRecord, LocalChange};
pub use path::RelPath;
pub use version::{Relation, Version};

/// The version of delocal, taken from the workspace at compile time.
///
/// Both crates inherit `workspace.package.version`, so this is also the
/// version the `delocal` binary reports.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod tests {
    use super::VERSION;

    #[test]
    fn version_is_semver_shaped() {
        let parts: Vec<&str> = VERSION.split('.').collect();
        assert_eq!(parts.len(), 3, "expected major.minor.patch, got {VERSION}");
        for part in parts {
            part.parse::<u64>()
                .expect("each version component is a number");
        }
    }
}
