//! `delocal-engine`: the pure sync engine (DESIGN.md §7, §8 and Appendix B).
//!
//! The engine takes events (scan results, incoming messages, timer ticks) and
//! returns actions (write file, send message, record history). It does no I/O
//! and depends on nothing that does. Time and randomness are inputs:
//! timestamps and fresh identifiers arrive in events, generated by the host.
//!
//! Phase 1 builds this crate up one step at a time (§15). So far:
//!
//! - [`id`]: node, folder and batch identifiers (§4), hostnames (§7.1)
//! - [`version`]: version vectors, comparison, merge, the local-change rule (§7.2)
//! - [`path`]: validated relative paths (§7.1)
//! - [`entry`]: index entries and content equality (§7.1, §7.6)
//! - [`index`]: the per-folder index, local changes, tombstones (§7.1, §7.2, §7.7)
//! - [`time`]: timestamps as inputs and the batch window constants (§7.4)
//! - [`rules`]: per-folder thresholds and limits (§8.1, §6.5)
//! - [`batch`]: batch formation, the summary, decisions, the apply set (§7.4)
//! - [`brake`]: the H1 and H2 rules, one function for sender and receiver (§8.1)
//! - [`quarantine`]: held batches and the versions they hold (§8.2)
//! - [`want`]: the want-list, source selection, deadlines, ordering (§7.5, §6.5)
//! - [`conflict`]: the winner rule, the merged version `M`, conflict-copy names (§7.6)
//! - [`folder`]: per-folder state: window, scan bracket, accepted work (§7.3, §7.4)
//! - [`parts`]: the persisted parts and how their changes are reported (§11)
//! - [`engine`]: the `Engine`, its `Event`s and `Action`s (§7)

// Tests may unwrap and expect (CLAUDE.md conventions); production code may not.
#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

pub mod batch;
pub mod brake;
pub mod conflict;
pub mod engine;
pub mod entry;
pub mod folder;
pub mod id;
pub mod index;
pub mod parts;
pub mod path;
pub mod quarantine;
pub mod rules;
pub mod time;
pub mod version;
pub mod want;

pub use batch::{
    ApplyItem, ApplyMode, ApplySet, Batch, BatchDecision, BatchRole, Classified, Decision, Summary,
};
pub use brake::{HoldReason, Verdict};
pub use conflict::{ConflictCopy, Resolution, Side, Winner};
pub use engine::{Action, Engine, Event, NodeConfig, Outbound};
pub use entry::{ContentHash, Entry, Kind, Observed};
pub use folder::{
    ApplyOutcome, Approved, Deferred, DeferredReason, Displace, Fetched, FolderState, FolderStatus,
    HostStep, Next, Paused, Queued, Received, Requested, RevertOutcome, ScanState, Ticked,
    UserDecision, WaitReason, Window,
};
pub use id::{BatchId, FolderId, HostName, NodeId};
pub use index::{ChangeKind, Index, IndexRecord, LocalChange, Pending, Reverted};
pub use path::RelPath;
pub use quarantine::{HeldItem, HeldRow, Quarantine, Quarantined};
pub use rules::Rules;
pub use time::Timestamp;
pub use version::{Relation, Version};
pub use want::{FetchReport, Tier, Want, WantList, WantState};

/// The version of delocal, taken from the workspace at compile time.
///
/// Both crates inherit `workspace.package.version`, so this is also the
/// version the `delocal` binary reports.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod tests {
    use super::VERSION;

    #[test]
    fn version_is_semver_shaped() {
        let parts: Vec<&str> = VERSION.split('.').collect();
        assert_eq!(parts.len(), 3, "expected major.minor.patch, got {VERSION}");
        for part in parts {
            part.parse::<u64>()
                .expect("each version component is a number");
        }
    }
}
